### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [acumulus8/tea-cozy#7]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/acumulus8/tea-cozy/blob/33c6a946700c1d291cb15b05adb4fde39258b08d/index.html#L37

**Comment by acumulus8** [comment]
i did do that for all images in html. is there a way to do it for background images set in css?

**Comment by martoio** [comment]
Ah sorry about this issue...I didn't see that the alt attribute was there because I was viewing the document without syntax highlighting. My bad, just close this one out and don't worry about it.

You don't add it to CSS because it's not needed. The idea of the alt attribute is to give more explanation about the content (for disabled users or if the image fails to load for some reason). Adding images in CSS is mostly about making things aesthetically pleasing (ie, it isn't part of the _content_). (FYI: https://stackoverflow.com/a/1469139 - when to use img and CSS if you are interested)

Again, sorry for opening this issue, my mistake, thanks for catching it!
@acumulus8
